name: build postgres osx
run-name: ${{ github.actor }} is building postgres ðŸš€
on:
  - push
  - workflow_dispatch
jobs:
  build-osx:
    runs-on: macos-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out postgres code
        uses: actions/checkout@v4
        with:
          repository: postgres/postgres
          ref: refs/tags/REL_16_2
          fetch-tags: true
      - run: echo "ðŸ’¡ The postgres repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: ls -al --recursive pgsql || echo "directory pgsql does not exist"
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - run: curl https://raw.githubusercontent.com/eitco/build-postgres/${{ github.ref_name }}/build.sh > build.sh && chmod +x build.sh
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: ./build.sh
      - run: ls -al --recursive pgsql || echo "directory pgsql does not exist"
      - uses: ncipollo/release-action@v1.14.0
        with:
          name: "postgres-16.2-os-x"
          body: "postgres 16.2 os-x"
          artifacts: "postgres.tar.gz"
